### ISSUE TITLE
Road Map

### ISSUE THREAD

**Issue by IWriteThings** [WowzaMediaSystems/wse-rest-library-php#26]
Things to do as per end of phone call with Wowza.

ToDo List

- [x] Packagist Upload #24 
- [x] Point Release System #27 
- [x] Create and follow ruleset for branches / master, dev, feature test releases #27 
- [ ] Add guzzle support / dependency support
- [x] Lint the project / meet code standards
- [ ] Comments Added
- [ ] Use wiki to document
- [ ] move 'tests' to examples
- [ ] Create actual tests and use a testing system (think phpunit)
- [ ] Move config to yaml and add yaml parsing dependency
- [ ] Create contribution guide

References

- http://www.php-fig.org/
- https://packagist.org/
- https://getcomposer.org/
- https://thephpleague.com/

**Comment by IWriteThings** [comment]
Small update - We are now on packagist

https://packagist.org/packages/wowza/wse-rest-library-php

**Comment by IWriteThings** [comment]
Small update - We are now using Scrutinizer for code quality / style review.

**Comment by haridarshan** [comment]
@IWriteThings 

Few classes have complexity > 5, need to bring them to <=5

**Comment by akeller** [comment]
Is this todo list still valid?
